# Generated by Django 4.2.6 on 2024-01-17 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agendapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="imformation",
            new_name="information",
        ),
    ]
