# Generated by Django 4.2.6 on 2024-01-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendapp", "0004_alter_information_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="category",
            field=models.CharField(
                choices=[("写真", "写真"), ("お題", "お題")], default=1, max_length=100
            ),
            preserve_default=False,
        ),
    ]
