# Generated by Django 4.2.6 on 2024-07-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agendapp", "0007_alter_information_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="topics/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="answer",
            name="odai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="agendapp.information",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="category",
            field=models.CharField(
                choices=[("写真", "写真"), ("お題", "お題")], max_length=100
            ),
        ),
    ]
