# Generated by Django 4.2.6 on 2024-07-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agendapp", "0008_topic_alter_answer_odai_alter_information_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="odai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agendapp.information"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="category",
            field=models.CharField(choices=[("写真", 1), ("お題", 2)], max_length=100),
        ),
    ]
